"""Add Exercise and ExerciseAttempt models and relationships

Revision ID: 2c31b1edf70d
Revises: c6476af52060
Create Date: 2025-06-15 16:29:42.747918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2c31b1edf70d'
down_revision = 'c6476af52060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('exercise_type', sa.Enum('MULTIPLE_CHOICE', 'FILL_IN_THE_BLANKS', 'SPEAKING', 'LISTENING', 'MATCHING', 'VOCABULARY_GAME', 'GRAMMAR_DRILL', name='exercisetype'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=255), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('difficulty_level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='exercisedifficultylevel'), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('exercise_attempt',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score_earned', sa.Integer(), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('feedback_given', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.exercise_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.drop_table('exercises')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('exercise_type', sa.VARCHAR(length=18), nullable=False),
    sa.Column('question_text', sa.TEXT(), nullable=True),
    sa.Column('audio_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('correct_answer', sa.TEXT(), nullable=True),
    sa.Column('options', sqlite.JSON(), nullable=True),
    sa.Column('difficulty_level', sa.VARCHAR(length=6), nullable=True),
    sa.Column('points', sa.INTEGER(), nullable=True),
    sa.Column('time_limit', sa.INTEGER(), nullable=True),
    sa.Column('order_index', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exercise_attempt')
    op.drop_table('exercise')
    # ### end Alembic commands ###
