"""Add Authentication model

Revision ID: 4f4822ee5ac0
Revises: 936ab3ed352d
Create Date: 2025-06-06 19:58:57.873580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4822ee5ac0'
down_revision = '936ab3ed352d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentication',
    sa.Column('auth_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('login_attempts', sa.Integer(), nullable=False),
    sa.Column('account_locked', sa.Boolean(), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('password_reset_token', sa.String(length=128), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('session_token', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('auth_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authentication')
    # ### end Alembic commands ###
