"""empty message

Revision ID: b1c85111c9a1
Revises: 4f4822ee5ac0
Create Date: 2025-06-15 12:49:28.095877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c85111c9a1'
down_revision = '4f4822ee5ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('course_image_url', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('exercise_type', sa.Enum('MULTIPLE_CHOICE', 'FILL_IN_THE_BLANKS', 'SPEAKING', 'LISTENING', 'MATCHING', 'VOCABULARY_GAME', 'GRAMMAR_DRILL', name='exercisetype'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=255), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('difficulty_level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='exercisedifficultylevel'), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('lessons_completed', sa.Integer(), nullable=True),
    sa.Column('exercises_completed', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('average_accuracy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('skill_scores', sa.JSON(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='_user_course_uc')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    op.drop_table('progress_tracking')
    op.drop_table('exercises')
    op.drop_table('courses')
    # ### end Alembic commands ###
