"""Add CourseContent model

Revision ID: c6476af52060
Revises: 407abbdb0d26
Create Date: 2025-06-15 13:57:58.372846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6476af52060'
down_revision = '407abbdb0d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content_type', sa.Enum('TEXT', 'VIDEO', 'AUDIO', 'DOCUMENT', 'IMAGE', name='contenttype'), nullable=False),
    sa.Column('content_url', sa.String(length=255), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_contents')
    # ### end Alembic commands ###
